### ISSUE TITLE
Fix Hybrid Element positon determination

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium-inspector#154]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## Environment

- I am running Appium Desktop version _2021.9.1_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

## The problem
HTML elements in an Hybrid app are not positioned properly, this has been fixed in Appium Desktop, see
https://github.com/appium/appium-desktop/pull/1906. This needs to be ported to Appium Inspector

**Comment by wswebcreation** [comment]
Fixed

**Comment by avenstewart** [comment]
I have updated to the latest 1.22 Appium Server GUI as well as the latest inspector patch 2021.9.2, and I am still experiencing this issue [Android 9, Chrome 96] on a hybrid Cordova application. Appium components deleted from android device, app cache cleared, Appium server and inspector restarted, device restarted, app reinstalled, error still persists - along with https://github.com/appium/appium-inspector/issues/150.
